#!/usr/bin/env python3
#
# Copyright 2014 Sean Alexandre
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import netaddr
import unittest
import sys

sys.path.append('..')
from netstat import *

# Open debug output file
debug_output = None
#debug_output_file_name = "./debug-output.txt"
debug_output_file_name = None
if not debug_output_file_name is None:
    debug_output = open(debug_output_file_name, 'w')

def log(cls, message):
    if not debug_output is None:
        debug_output.write(message)
        debug_output.write('\n')
        debug_output.flush()

class TestSocketInfo(unittest.TestCase):
    def test_parsing_hex2dec(self):
        self.assertEqual(SocketInfo._hex2dec("0"), "0")
        self.assertRaises(ValueError, SocketInfo._hex2dec, "")
        self.assertEqual(SocketInfo._hex2dec("FF"), "255")
        self.assertRaises(ValueError, SocketInfo._hex2dec, "FFz")
        self.assertEqual(SocketInfo._hex2dec("abcdef1234"), "737894404660")

    def test_parsing_ip(self):
        self.assertEqual(SocketInfo._ip("FFFFFFFF"), "255.255.255.255")
        self.assertRaises(MonitorException, SocketInfo._ip, "0")
        self.assertEqual(SocketInfo._ip("293DA8DF"), "223.168.61.41")

    def test_parsing_ip6(self):
        self.assertEqual(
            netaddr.IPAddress(SocketInfo._ip("B90D01200000000067452301EFCDAB89")), 
            netaddr.IPAddress("2001:db9::0123:4567:89ab:cdef"))
        self.assertEqual(SocketInfo._ip("0000000000000000FFFF00000100007F"), "127.0.0.1")
            
    def test_parsing_ip_port(self):
        self.assertEqual(SocketInfo._convert_ip_port("293DA8DF:0050"), ("223.168.61.41", "80"))

    def test_parsing_is_ip_addr_private(self):
        self.assertEqual(SocketInfo._is_ip_addr_private("172.27.0.30"), True)
        self.assertEqual(SocketInfo._is_ip_addr_private("fde4:8dba:82e1::1"), True)
        self.assertEqual(SocketInfo._is_ip_addr_private("74.125.224.194"), False)
        self.assertEqual(SocketInfo._is_ip_addr_private("2001:db9::0123:4567:89ab:cdef"), False)

    def test_parsing_is_ip_addr_loopback(self):
        self.assertEqual(SocketInfo._is_ip_addr_loopback("127.0.0.1"), True)
        self.assertEqual(SocketInfo._is_ip_addr_loopback("::1"), True)

    def test_construct(self):
        """
        sl   local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode ref pointer drops             
        268: 0100007F:0035 00000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 139165 2 0000000000000000 0        
        """
        line = "268: 0100007F:0035 00000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 139165 2 0000000000000000 0"
        info = SocketInfo._create_from_line("tcp", line)
        info.finish_initializing()
        self.assertEqual(info.state, "CLOSE")
        self.assertEqual(info.local_host, "127.0.0.1")
        self.assertEqual(info.local_port, "53")
        self.assertEqual(info.fingerprint, "type:tcp local_address:0100007F:0035 rem_address:00000000:0000")

    def setUp(self): pass

class TestFilters(unittest.TestCase):
    def test_filter_exe(self):
        # Test match
        filter = GenericFilter("test", exe="/usr/sbin/ntpd")
        socket_info = SocketInfo._create_from_params(exe="/usr/sbin/ntpd")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(exe="/usr/sbin/ntpd2")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_cmdline(self):
        # Test match
        filter = GenericFilter("test", cmdline="/usr/bin/mpop -Q account1")
        socket_info = SocketInfo._create_from_params(cmdline="/usr/bin/mpop -Q account1")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(cmdline="/usr/bin/mpop")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_cmdline_is_re(self):
        # Test match
        filter = GenericFilter("test", cmdline="/usr/bin/[^ ]* -Q account1", cmdline_is_re=True)
        socket_info = SocketInfo._create_from_params(cmdline="/usr/bin/boop -Q account1")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(cmdline="/usr/bin/boop -R account1")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_user(self):
        # Test match
        filter = GenericFilter("test", user="root")
        socket_info = SocketInfo._create_from_params(user="root")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(user="www-data")
        self.assertFalse(filter.filter_out(socket_info))


    def test_filter_local_hosts(self):
        # Test match
        filter = GenericFilter("test", local_hosts="127.0.0.1")
        socket_info = SocketInfo._create_from_params(local_host="127.0.0.1")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(local_host="128.0.0.1")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_local_ports(self):
        # Test match
        filter = GenericFilter("test", local_ports="1234,5432,6789")
        socket_info = SocketInfo._create_from_params(local_port="1234")
        self.assertTrue(filter.filter_out(socket_info))
        socket_info = SocketInfo._create_from_params(local_port="6789")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(local_port="5555")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_remote_hosts(self):
        # Test match
        filter = GenericFilter("test", remote_hosts="www.somedomain.net,anotherdomain.com,www.andanother.org")
        socket_info = SocketInfo._create_from_params(remote_host_name="www.somedomain.net")
        self.assertTrue(filter.filter_out(socket_info))
        socket_info = SocketInfo._create_from_params(remote_host_name="www.andanother.org")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(remote_host_name="www.somedomain2.net")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_remote_ips(self):
        # Test match
        filter = GenericFilter("test", remote_ips="40.50.60.70,23.24.25.26,77.78.79.0/24")
        socket_info = SocketInfo._create_from_params(remote_host="23.24.25.26")
        self.assertTrue(filter.filter_out(socket_info))
        socket_info = SocketInfo._create_from_params(remote_host="77.78.79.80")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(remote_host="77.78.80.80")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_remote_ports(self):
        # Test match
        filter = GenericFilter("test", remote_ports="1234,5432,6789")
        socket_info = SocketInfo._create_from_params(remote_port="1234")
        self.assertTrue(filter.filter_out(socket_info))
        socket_info = SocketInfo._create_from_params(remote_port="6789")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(remote_port="5555")
        self.assertFalse(filter.filter_out(socket_info))

    def test_filter_state(self):
        # Test match
        filter = GenericFilter("test", states="SYN_SENT,ESTABLISHED")
        socket_info = SocketInfo._create_from_params(state="ESTABLISHED")
        self.assertTrue(filter.filter_out(socket_info))

        # Test mismatch
        socket_info = SocketInfo._create_from_params(state="CLOSED")
        self.assertFalse(filter.filter_out(socket_info))

    def setUp(self): pass

def runAllTests():
    passed = True
    # TestSocketInfo
    suite = unittest.TestLoader().loadTestsFromTestCase(TestSocketInfo)
    ret = unittest.TextTestRunner(verbosity=3).run(suite)
    if not ret.wasSuccessful():
        passed = False

    # TestFilters
    suite = unittest.TestLoader().loadTestsFromTestCase(TestFilters)
    ret = unittest.TextTestRunner(verbosity=3).run(suite)
    if not ret.wasSuccessful():
        passed = False

    return passed

def runSpecificTests():
    passed = True
    suite = unittest.TestSuite()

    #suite.addTest(TestSocketInfo('test_construct'))
    suite.addTest(TestSocketInfo('test_parsing_ip6'))
    #suite.addTest(TestSocketInfo('test_parsing_ip_port'))

    ret = unittest.TextTestRunner(verbosity=3).run(suite)
    if not ret.wasSuccessful():
        passed = False

    return passed

def main():
    passed = runAllTests()
    #passed = runSpecificTests()
    if passed:
        sys.exit()
    else:
        sys.exit("Test(s) failed!")

if __name__ == '__main__':
    main()

