#!/bin/bash

# "Checks all" by running: tests, pylint, and mypy.

function message() {
    printf "$1\n"
}

function errMessage() {
    printf "ERROR: $1\n"
} >&2

function errExit() {
    errMessage "$1"
    exit 1
}

# cd to the directory this script is in
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"

# Run tests
cd test
./test_netstat &> /dev/null || errExit "Tests failed"
cd ..
message "Check 1/5: Tests passed"

# Run pylint on netstat
pylint netstat &> /dev/null || errExit "Pylint on netstat module failed"
message "Check 2/5: Pylint on netstat module passed"

# Run pylint on tests
cd test
pylint test_netstat &> /dev/null || errExit "Pylint on tests failed"
cd ..
message "Check 3/5: Pylint on tests passed"

# Run mypy on netstat
mypy netstat &> /dev/null || errExit "Mypy on netstat module failed"
message "Check 4/5: Mypy on netstat module passed"

# Run mypy on tests
mypy test/test_netstat &> /dev/null || errExit "Mypy on tests failed"
message "Check 5/5: Mypy on netstat module passed"

echo "Success! All checks passed."
