#!/usr/bin/python3
#
# Copyright 2012 Sean Alexandre
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
from netstat import GenericFilter
from netstat import Monitor

def main():

    # Check for root permissions, so filters work and connection details can be looked up.
    if os.geteuid() != 0:
        print("ERROR: Root permissions needed, to lookup connection details.")
        sys.exit(-1)

    # Create filters
    closing_states = ['FIN_WAIT1', 'FIN_WAIT2', 'TIME_WAIT', 'CLOSE', 'CLOSE_WAIT', 'LAST_ACK', 'CLOSING']
    filters = [ 
        # Trusted
        GenericFilter(exe='/usr/sbin/ntpdate', user='root'),
        GenericFilter(exe='/sbin/dhclient', user='root'),
        GenericFilter(exe='/usr/sbin/dnsmasq', user='root'),
        GenericFilter(exe='/usr/sbin/dnsmasq', user='nobody'),

        # Firefox expected
        GenericFilter(exe='/usr/lib/firefox/firefox', user='ff', remote_ports = ['53', '80', '443', '8080']),

        # Claws Mail
        GenericFilter(exe='/usr/bin/claws-mail', user='sean', remote_hosts = ['.pobox.com', '.riseup.net', '.mayfirst.org' ]),
        GenericFilter(exe='/usr/bin/claws-mail', user='sean', remote_ports = ['53']),

        #  VirtualBox: Monitor VMs from within VM.
        GenericFilter(exe='/usr/lib/virtualbox/VirtualBox'),

        # ssh
        GenericFilter(cmdline='ssh sean864@login.trilug.org', user='sean'),
        GenericFilter(cmdline='ssh sean@moose', user='sean'),
        GenericFilter(cmdline='ssh gamma@85.17.244.26', user='sean'),

        # netstat-monitor DNS lookups
        GenericFilter(cmdline='/usr/bin/python3 ./netstat-monitor', remote_ports = ['53']),

        # MoinMoin
        GenericFilter(cmdline='/usr/bin/python /home/sean/moin-1.9.4/wikiserver.py', local_hosts = ['127.0.0.1'], local_ports = ['8080'], user = 'sean'),
        GenericFilter(cmdline='/usr/bin/vim /tmp/vimperator-localhost-1.tmp', remote_hosts = ['127.0.0.1'], remote_ports = ['8080'], user = 'ff'),

        # upstart-udev-bridge: Seems to have closing connections from firefox, claws, etc. Why?
        GenericFilter(exe='/sbin/upstart-udev-bridge', user='root', states = closing_states)
    ]

    # Monitor
    try:
        monitor = Monitor(interval = 1, filters = filters)
        monitor.monitor()
    except KeyboardInterrupt:
        print('')

if __name__ == '__main__':
    main()

